# generate-types


print("// types-generated.ts - Automatically generated types from basscss source code")
print("// Generated by generate-types.py ")
print("/* tslint-disable */")

types = ("p", "m")
subs = ("x", "y", "l", "r", "t", "b")

for tipe in types:
    print(f"export type {'Padding' if tipe == 'p' else 'Margin'} = ", end="")
    res = []
    for n in range(0, 6):
        res.append(f'"{tipe}{n}"')
        for sub in subs:
            res.append(f'"{tipe}{sub}{n}"')
    print(" | ".join(res), end="")
    print(";\n")
