// types-generated.ts - Automatically generated types from basscss source code
// Generated by generate-types.py 
/* tslint-disable */
export type Padding = "p0" | "px0" | "py0" | "pl0" | "pr0" | "pt0" | "pb0" | "p1" | "px1" | "py1" | "pl1" | "pr1" | "pt1" | "pb1" | "p2" | "px2" | "py2" | "pl2" | "pr2" | "pt2" | "pb2" | "p3" | "px3" | "py3" | "pl3" | "pr3" | "pt3" | "pb3" | "p4" | "px4" | "py4" | "pl4" | "pr4" | "pt4" | "pb4" | "p5" | "px5" | "py5" | "pl5" | "pr5" | "pt5" | "pb5";

export type Margin = "m0" | "mx0" | "my0" | "ml0" | "mr0" | "mt0" | "mb0" | "m1" | "mx1" | "my1" | "ml1" | "mr1" | "mt1" | "mb1" | "m2" | "mx2" | "my2" | "ml2" | "mr2" | "mt2" | "mb2" | "m3" | "mx3" | "my3" | "ml3" | "mr3" | "mt3" | "mb3" | "m4" | "mx4" | "my4" | "ml4" | "mr4" | "mt4" | "mb4" | "m5" | "mx5" | "my5" | "ml5" | "mr5" | "mt5" | "mb5";
